#!/bin/sh
set -e
cd "$(dirname "$0")"/../

source iptables.conf

if [ "$SYSCTL" = "" ]; then
    echo "Update SYSCTL path and try again."
    exit 1
fi

$SYSCTL net.ipv6.conf.all.disable_ipv6="1"
$SYSCTL net.ipv6.conf.default.disable_ipv6="1"
$SYSCTL net.ipv6.conf.lo.disable_ipv6="1"
